# trigger build 010
language: objective-c
osx_image: xcode10.1
xcode_project: Capital.xcodeproj
xcode_scheme: Capital
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone 6s
env:
  global:
    - CC_TEST_REPORTER_ID=db15990215dc6d274f01ad4cbe188a17fdf5fc057f96bff6112f58388eafaad5
env:
  - SWIFT_VERSION=4.2
os: osx

install:
  - gem install xcpretty

before_script:
  # - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  # - chmod +x ./cc-test-reporter
  # - file ./cc-test-reporter
  # - ./cc-test-reporter before-build

script:
  - xcodebuild -project Capital.xcodeproj -scheme Capital -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.1,name=iPhone 6s" -configuration Debug -PBXBuildsContinueAfterErrors=0 SWIFT_VERSION=$SWIFT_VERSION build test

after_script:
  - bash <(curl -s https://codecov.io/bash)
 # - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  # - ./cc-test-reporter format-coverage -t gcov ./coverage/gcov.info
  # - ./cc-test-reporter upload-coverage
  # - ls
  # - ls ./
  # - ls ./coverage

